POST http://localhost:3333/categories HTTP/1.1
Content-Type: application/json

{
  "name": "Catdsdsesssgdsory superteddsssdssssssssst"
}

###

GET http://localhost:3333/categories HTTP/1.1

###
GET http://localhost:3333/categories?q=Lanches HTTP/1.1

###

DELETE http://localhost:3333/categories/12dcff68-44bd-438f-9381-5f0f32082309


