POST http://localhost:3333/categories HTTP/1.1
Content-Type: application/json

{
  "name": "LanchdDdDdedss "
}

###

GET http://localhost:3333/categories HTTP/1.1

###
GET http://localhost:3333/categories?q=Lanches HTTP/1.1

###

DELETE http://localhost:3333/categories/fa5285dc-e1a5-4d16-94f9-a419c3b7aa3c


###

PUT http://localhost:3333/categories HTTP/1.1 
Content-Type: application/json

{
    "guid": "1dec99c3-9212-4dea-8584-240fb2c44158"
}

